# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: gitclone 
        run: git clone https://github.com/prajeshgupta24/testRepo.git
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: docker installation 
        run: curl -fsSL https://get.docker.com | sh 

      # Runs a set of commands using the runners shell
      - name: docker login 
        run: docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
      - name: docker build 
        run: cd testRepo && docker build . -t fast_api:prajeshgupta
      - name: test
        run: echo "hello"
      - name: docker tag & push  
        run: docker tag fast_api:prajesh prajeshgupta24/testlkm:satyam && docker push prajeshgupta24/testlkm:prajesh
